### PR TITLE
Scheduled Job to Mark Past Shifts as 'Complete'

### PR DESCRIPTION
**Pull request by cdcarter**
Caroline Renard writes to me:
> I now have two clients who have asked for the same thing.  One is a film festival so things are VERY intensive, the other is just busy...  Anyway, they would like to automate the process of recording hours worked by their volunteers - what they are looking for is that the system would just update the Status to "Completed" and the Hours Tracked for any volunteer who is confirmed for a Shift once the shift is over.  (Vol Manager will manually handle the exceptions, like the No Shows.)  

> Updating a Volunteer Hours record seems straightforward enough, but the problem is how to trigger the updates.  It can't be a workflow, I think, because no-one will be editing the record.  But it might be possible to do with a Scheduled Job, I guess, that looks for completed Shifts each night, and runs the updates.  I've not built a Scheduled Job before, but that seemed like a possible solution to me.

So, I built a scheduled job. 

Documentation is located at: https://dl.dropboxusercontent.com/spa/q8pc7mthv83x9i1/volunteers-auto-completer/index.html

I have no clue if this is something you'd want in core, but I thought I'd throw the code your way (as well as my failed attempts to rebase...)

### CODE REVIEW

**Comment by cdcarter** [comment]
This implementation of the feature may have the same issue #158 has.

**Comment by davidhabib** [comment]
Thanks for the contribution Christian.  Unfortunately, I don't think this will scale correctly in organizations with many Jobs and Hours.  You really need to do this type of scheduled fixup using batches to get over various system limits.  Check out https://github.com/davidhabib/Volunteers-for-Salesforce/blob/master/src/classes/VOL_BATCH_Recurrence.cls to see how the scheduler works.  The key points are that Schedulable.Execute() invokes database.ExecuteBatch().  Then the batch job's start method queries for all the records with a getQueryLocator, and the batch's Execute method then gets called with a set of records to operate on.  The only weirdness in this example is it does an ExecuteBatch() with a batch size of only 1, since each JobRecurrenceSchedule can spawn off hundreds of shifts and hours being created.  Usually, one would be doing batches of anywhere from 20 - 200 depending on the complexity of what the batch had to do.

Let me know if you have more questions.  If you want to tackle the changes I suggest, that would be great!  if you don't have time, I can do this work, but it will be prioritized on the with list against the many other features waiting to be done!

**Comment by cdcarter** [comment]
I figured this should probably be batched, but I was gonna try and get by with it anyway. I'll work on it. I haven't touched batches since I started studying for 501, so I should brush up anyway.

**Comment by cdcarter** [comment]
I've now learned a LOT about testing batchable apex!

**Comment by davidhabib** [comment]
Hi Christian, I've been thinking about this functionality, and wondering if having it scheduled is the best way to go vs a button that could do it per campaign or job.  what are your thoughts?  do you think groups who want this behavior will always want it to happen for all jobs at once?

**Comment by cdcarter** [comment]
I think leaving the opportunity for it to be scheduled is useful. For large festivals (my vol mgmt background), we really do just expect that volunteers show up and venue managers only report no-shows. Letting it just run each night keeps progress numbers accurate without having to manually perform an action before reporting. 

That said, I see the value in this only being the case for some jobs/campaigns, and I also see the value in letting orgs run this process manually if they don't want to commit to a scheduled job.

Perhaps a full version of the feature would be a button on campaign (or job? I tend to use campaign hierarchies but that's not necessarily how everyone does it), as well as a checkbox on the campaign (or job) to opt in or out of the scheduled process (like what currently exists on the Hours record).

**Comment by cdcarter** [comment]
Caroline and I did a nice back and forth about where her clients who have requested this feature would need it, and after discussing what the behavior would look like with checkboxes on campaign, job, and hours record, we came to the conclusion that just a checkbox on Job and Hours is sufficient, and the way it behaved on Campaign would be unintuitive. 

The design we propose is an "opt-in" checkbox on volunteer job (which the org can default however they want) and an "opt-out" checkbox on the hours record. The only way to get the scheduled job to complete the record would be TRUE on the job and FALSE on the hours record. 

Caroline didn't believe that a button to do this process would be very useful, since Mass Edit is only a few more clicks. This is just really a useful feature for Vol Mgrs that only care about no-shows and mostly report in aggregate.

I'm going to clean up this PR soon and send one last revision. Then, either you merge it or Caroline just keeps using the unmanaged code! :)

Thanks David

**Comment by davidhabib** [comment]
Thanks for the update.  any chance you or Caroline want to provide some documentation I can easily slip into the user's guide and installation & configuration guide?  not a requirement, but would be nice to have!  thanks!

**Comment by cdcarter** [comment]
Of course I'll provide docs!

**Comment by cdcarter** [comment]
updated with a checkbox on Job. docs coming next.

**Comment by cdcarter** [comment]
Hey David, I owe you docs! Do you have a format that you'd prefer me to work in, or should I just update the clarify docs? https://dl.dropboxusercontent.com/spa/q8pc7mthv83x9i1/volunteers-auto-completer/index.html

**Comment by bethbbc** [comment]
Hi, folks! I'm 99% sure this could be simply a time-based WFR/PB that queues upon Status=Confirmed and fires upon shift time. Am I missing something?

**Comment by cdcarter** [comment]
I just did a rudimentary test of Beth's "uh duh" and it appears to work. Let me check in with Caroline if I'm missing anything specific to her use case, but I think that's a better way of handling this and more in line with how V4SF works.

**Comment by cdcarter** [comment]
I'm closing this, as the WFR solution is more than sufficient.

**Comment by davidhabib** [comment]
Thanks @cdcarter

**Comment by cdcarter** [comment]
Aren't you on PTO?

**Comment by davidhabib** [comment]
Friday's is my normal day off, but I still try to keep up on email at the end of the day!  next week will be harder, as I'm off skiing at Whistler!

**Pull request closed without merging**
